organization:
  id: o-xxxx
env:
  tools:    
    account: '1234567890'
    region: 'ap-southeast-2'
  dev:    
    account: '1234567890'
    region: 'ap-southeast-2'
  test:
    account: '1234567890'
    region: 'ap-southeast-2'
  prod:    
    account: '1234567890'
    region: 'ap-southeast-2'
